import { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service - Root News',
  description: 'Terms of Service for Root News app. Read our terms and conditions for using our AI-powered news service.',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-dark-950">
      <Header />
      <main className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="prose prose-invert max-w-none">
            <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
            <p className="text-dark-300 text-lg mb-8">
              Last updated: {new Date().toLocaleDateString()}
            </p>

            <div className="space-y-8 text-dark-300">
              <section>
                <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                <p className="mb-4">
                  By downloading, installing, or using the Root News application, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
                <p className="mb-4">
                  Root News is a mobile application that aggregates news from various sources and uses artificial intelligence to provide summarized news content. Our service is designed to help users stay informed efficiently.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">3. User Responsibilities</h2>
                <p className="mb-4">
                  As a user of Root News, you agree to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Use the service only for lawful purposes</li>
                  <li>Not attempt to reverse engineer or hack the application</li>
                  <li>Not share your account credentials with others</li>
                  <li>Respect intellectual property rights of news sources</li>
                  <li>Not use the service to spread misinformation</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">4. Content and Accuracy</h2>
                <p className="mb-4">
                  While we strive to provide accurate news summaries, Root News does not guarantee the accuracy, completeness, or timeliness of the content. News summaries are generated by AI and may contain errors. Users should verify important information from original sources.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">5. Intellectual Property</h2>
                <p className="mb-4">
                  The Root News application, including its design, functionality, and AI algorithms, is owned by us and protected by intellectual property laws. News content belongs to the respective publishers and is used under fair use provisions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">6. Privacy</h2>
                <p className="mb-4">
                  Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your information.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">7. Limitation of Liability</h2>
                <p className="mb-4">
                  Root News and its developers shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">8. Service Availability</h2>
                <p className="mb-4">
                  We strive to maintain service availability but do not guarantee uninterrupted access. We may temporarily suspend service for maintenance, updates, or other operational reasons.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">9. Termination</h2>
                <p className="mb-4">
                  We reserve the right to terminate or suspend access to our service at any time, with or without cause, and with or without notice.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">10. Changes to Terms</h2>
                <p className="mb-4">
                  We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">11. Governing Law</h2>
                <p className="mb-4">
                  These terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mb-4">12. Contact Information</h2>
                <p className="mb-4">
                  If you have any questions about these Terms of Service, please contact us at:
                </p>
                <div className="bg-dark-900 p-4 rounded-lg">
                  <p>Email: legal@rootnews.com</p>
                  <p>Address: [Your Company Address]</p>
                </div>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
} 